import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { useToast } from "@/hooks/use-toast";
import { Camera, ChevronRight, ChevronLeft, Check, Plus, Trash2 } from "lucide-react";
import logo from "@/assets/verifiedly-logo.webp";
import { motion, AnimatePresence } from "framer-motion";
import { recordStripeAgreement } from "@/lib/stripe-agreement";
import PayoutsChecklist from "@/components/payouts/PayoutsChecklist";

const THEMES = [
  { id: "default", label: "Classic", bg: "bg-background", accent: "bg-foreground" },
  { id: "midnight", label: "Midnight", bg: "bg-[hsl(230,25%,12%)]", accent: "bg-[hsl(230,60%,60%)]" },
  { id: "sunset", label: "Sunset", bg: "bg-[hsl(20,30%,97%)]", accent: "bg-[hsl(20,90%,55%)]" },
  { id: "forest", label: "Forest", bg: "bg-[hsl(150,20%,96%)]", accent: "bg-[hsl(150,60%,35%)]" },
  { id: "ocean", label: "Ocean", bg: "bg-[hsl(200,30%,96%)]", accent: "bg-[hsl(200,80%,45%)]" },
  { id: "lavender", label: "Lavender", bg: "bg-[hsl(270,30%,96%)]", accent: "bg-[hsl(270,60%,55%)]" },
];

const CREATOR_CATEGORIES = [
  "Player", "Musician", "Artist", "Influencer",
  "Coach", "Trainer", "Content Creator",
  "Podcaster", "Streamer", "Photographer",
  "Entrepreneur", "Writer", "Designer", "Developer",
  "Fitness", "Chef", "Educator",
];

const BUSINESS_CATEGORIES = [
  "Brand", "Agency", "Team", "Organization",
  "Startup", "Non-Profit", "E-Commerce", "Media Company",
];

const Onboarding = () => {
  const [step, setStep] = useState(0);
  const [userId, setUserId] = useState("");
  const [saving, setSaving] = useState(false);
  const [isOAuth, setIsOAuth] = useState(false);
  const navigate = useNavigate();
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Step 0: Account type & category
  const [accountType, setAccountType] = useState("creator");
  const [category, setCategory] = useState("");

  // Step 1: Profile basics (includes username for OAuth users)
  const [username, setUsername] = useState("");
  const [usernameAvailable, setUsernameAvailable] = useState<boolean | null>(null);
  const [checkingUsername, setCheckingUsername] = useState(false);
  const [displayName, setDisplayName] = useState("");
  const [bio, setBio] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");
  const [uploading, setUploading] = useState(false);
  const [instagram, setInstagram] = useState("");
  const [twitter, setTwitter] = useState("");
  const [youtube, setYoutube] = useState("");
  const [tiktok, setTiktok] = useState("");

  // Step 2: Links
  const [links, setLinks] = useState<{ title: string; url: string; icon: string }[]>([]);
  const [newLinkTitle, setNewLinkTitle] = useState("");
  const [newLinkUrl, setNewLinkUrl] = useState("");
  const [newLinkIcon, setNewLinkIcon] = useState("");

  // Step 3: Theme
  const [theme, setTheme] = useState("default");

  // Step: Stripe Connect (for creators/businesses)
  const [stripeConnecting, setStripeConnecting] = useState(false);
  const [stripeConnected, setStripeConnected] = useState(false);
  const [stripeAgreed, setStripeAgreed] = useState(false);

  const needsStripe = accountType === "creator" || accountType === "business";
  const steps = needsStripe ? ["Type", "Profile", "Links", "Payouts", "Theme"] : ["Type", "Profile", "Links", "Theme"];

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session) { navigate("/login"); return; }
      setUserId(session.user.id);
      const provider = session.user.app_metadata?.provider;
      const oauthUser = !!(provider && provider !== "email");
      setIsOAuth(oauthUser);
      
      setDisplayName(
        session.user.user_metadata?.display_name ||
        session.user.user_metadata?.full_name ||
        session.user.user_metadata?.name ||
        ""
      );
      setAccountType(session.user.user_metadata?.account_type || "creator");
      setCategory(session.user.user_metadata?.category || "");
      
      if (oauthUser && session.user.user_metadata?.avatar_url) {
        setAvatarUrl(session.user.user_metadata.avatar_url);
      }

      supabase.from("profiles").select("username, avatar_url").eq("id", session.user.id).maybeSingle().then(({ data }) => {
        if (data) {
          const autoGenerated = data.username && /^[a-f0-9]{32}$/.test(data.username);
          if (!autoGenerated && data.username) {
            setUsername(data.username);
          }
          if (data.avatar_url) setAvatarUrl(data.avatar_url);
        }
      });

      // Check stripe connection from private data
      (supabase.from("creator_private_data" as any).select("stripe_connect_account_id").eq("id", session.user.id).maybeSingle() as any).then(({ data }: any) => {
        if (data?.stripe_connect_account_id) setStripeConnected(true);
      });
    });

    // Handle Stripe Connect return
    const params = new URLSearchParams(window.location.search);
    if (params.get("stripe_onboarded") === "true") {
      setStripeConnected(true);
      window.history.replaceState({}, "", window.location.pathname);
    }
  }, [navigate]);

  // Username availability check
  useEffect(() => {
    if (username.length < 3) { setUsernameAvailable(null); return; }
    setCheckingUsername(true);
    const timer = setTimeout(async () => {
      const { data } = await supabase
        .from("profiles").select("id").eq("username", username.toLowerCase()).neq("id", userId).maybeSingle();
      setUsernameAvailable(!data);
      setCheckingUsername(false);
    }, 400);
    return () => clearTimeout(timer);
  }, [username, userId]);

  const handleAvatarUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 2 * 1024 * 1024) {
      toast({ title: "File too large", description: "Max 2MB.", variant: "destructive" });
      return;
    }
    setUploading(true);
    const ext = file.name.split(".").pop();
    const path = `${userId}/avatar.${ext}`;
    await supabase.storage.from("avatars").upload(path, file, { upsert: true });
    const { data: { publicUrl } } = supabase.storage.from("avatars").getPublicUrl(path);
    const url = `${publicUrl}?t=${Date.now()}`;
    await supabase.from("profiles").update({ avatar_url: url }).eq("id", userId);
    setAvatarUrl(url);
    setUploading(false);
  };

  const addLink = () => {
    if (!newLinkTitle.trim() || !newLinkUrl.trim()) return;
    let url = newLinkUrl.trim();
    if (!url.startsWith("http")) url = `https://${url}`;
    setLinks([...links, { title: newLinkTitle.trim(), url, icon: newLinkIcon.trim() || "🔗" }]);
    setNewLinkTitle(""); setNewLinkUrl(""); setNewLinkIcon("");
  };

  const removeLink = (i: number) => setLinks(links.filter((_, idx) => idx !== i));

  const handleFinish = async () => {
    if (username.length < 3) {
      toast({ title: "Username required", description: "Choose a username with at least 3 characters.", variant: "destructive" });
      setStep(1);
      return;
    }
    if (usernameAvailable === false) {
      toast({ title: "Username taken", description: "Please choose another username.", variant: "destructive" });
      setStep(1);
      return;
    }

    setSaving(true);
    try {
      // Use upsert so this works even if the profile row is missing
      // (e.g. trigger failed silently or user signed up before trigger fix).
      const { error: profileErr } = await supabase.from("profiles").upsert({
        id: userId,
        username: username.toLowerCase(),
        display_name: displayName,
        bio,
        account_type: accountType,
        category: category || null,
        social_links: { instagram, twitter, youtube, tiktok },
        theme_color: theme,
        onboarding_completed: true,
      }, { onConflict: "id" });
      if (profileErr) throw profileErr;

      if (links.length > 0) {
        const { error: linksErr } = await supabase.from("bio_links").insert(
          links.map((l, i) => ({
            creator_id: userId, title: l.title, url: l.url,
            icon: l.icon || null, sort_order: i,
          }))
        );
        if (linksErr) throw linksErr;
      }

      toast({ title: "You're all set! 🎉", description: "Your profile is live." });
      navigate(accountType === "fan" ? "/fan" : "/dashboard");
    } catch (err: any) {
      console.error("Onboarding finish error:", err);
      toast({ title: "Setup failed", description: err.message || "Could not complete setup. Please try again.", variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  const canProceed = () => {
    if (step === 1) return displayName.trim().length > 0 && username.length >= 3 && usernameAvailable !== false;
    // Payouts step index: 3 for creators/businesses (Type=0, Profile=1, Links=2, Payouts=3)
    // Payouts step is optional — can be skipped and completed later from settings
    return true;
  };

  const handleStripeConnect = async () => {
    if (!stripeAgreed) {
      toast({
        title: "Please accept the agreements",
        description: "You must agree to the Stripe Connected Account Agreement and our Terms before connecting.",
        variant: "destructive",
      });
      return;
    }
    setStripeConnecting(true);
    // Safety: if Stripe takes too long, re-enable the button so it never hangs
    const safety = setTimeout(() => setStripeConnecting(false), 15000);
    try {
      // Record agreement acceptance for audit trail (timestamp + IP + UA)
      await recordStripeAgreement(userId, "onboarding").catch((e) =>
        console.warn("Failed to record stripe agreement:", e)
      );
      const { data, error } = await supabase.functions.invoke("create-connect-account", {
        body: {
          return_url: `${window.location.origin}/onboarding?stripe_onboarded=true`,
          refresh_url: `${window.location.origin}/onboarding`,
        },
      });
      if (error) throw error;
      if (!data) throw new Error("No response from Stripe — please try again.");
      if (data.onboarded) {
        setStripeConnected(true);
        toast({ title: "Stripe connected! 🎉", description: "You're ready to receive payouts." });
      } else if (data.url) {
        window.location.href = data.url;
      } else if (data.error) {
        throw new Error(data.error);
      } else {
        throw new Error("Stripe didn't return an onboarding link. Please try again.");
      }
    } catch (err: any) {
      toast({ title: "Stripe connect failed", description: err?.message || "Unknown error", variant: "destructive" });
    } finally {
      clearTimeout(safety);
      setStripeConnecting(false);
    }
  };

  const categories = accountType === "business" ? BUSINESS_CATEGORIES : accountType === "creator" ? CREATOR_CATEGORIES : [];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <nav className="border-b border-border h-16 flex items-center px-4">
        <div className="container mx-auto flex items-center">
          <img src={logo} alt="Verifiedly" className="h-7" />
        </div>
      </nav>

      <div className="container mx-auto max-w-2xl px-4 pt-8">
        <div className="flex items-center gap-2 mb-2">
          {steps.map((_, i) => (
            <div key={i} className="flex-1">
              <div className={`h-2 rounded-full transition-colors ${i <= step ? "bg-primary" : "bg-muted"}`} />
            </div>
          ))}
        </div>
        <div className="flex justify-between text-xs text-muted-foreground mb-8">
          {steps.map((s, i) => (
            <span key={s} className={i === step ? "text-foreground font-medium" : ""}>{s}</span>
          ))}
        </div>
      </div>

      <div className="container mx-auto max-w-2xl px-4 flex-1">
        <AnimatePresence mode="wait">
          <motion.div
            key={step}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            {step === 0 && (
              <div className="space-y-6">
                <div>
                  <h1 className="text-2xl font-display font-bold">What type of account?</h1>
                  <p className="text-muted-foreground mt-1">This helps us personalize your experience</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {[
                    { value: "fan", label: "Fan", desc: "Follow creators, buy products" },
                    { value: "creator", label: "Creator / Player", desc: "Sell products, build an audience" },
                    { value: "business", label: "Business", desc: "Post campaigns, find creators" },
                  ].map(t => (
                    <button
                      key={t.value}
                      onClick={() => { setAccountType(t.value); setCategory(""); }}
                      className={`rounded-xl border-2 p-5 text-left transition-all ${accountType === t.value ? "border-primary ring-2 ring-primary/20" : "border-border hover:border-muted-foreground/30"}`}
                    >
                      <p className="font-display font-semibold">{t.label}</p>
                      <p className="text-sm text-muted-foreground mt-1">{t.desc}</p>
                    </button>
                  ))}
                </div>

                <div>
                  <Label>Category</Label>
                  <div className="grid grid-cols-3 gap-2 mt-2">
                    {categories.map(c => (
                      <button
                        key={c}
                        onClick={() => setCategory(c.toLowerCase())}
                        className={`px-3 py-2 rounded-lg text-sm font-medium transition-colors ${category === c.toLowerCase() ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground hover:bg-muted"}`}
                      >
                        {c}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {step === 1 && (
              <div className="space-y-6">
                <div>
                  <h1 className="text-2xl font-display font-bold">Set up your profile</h1>
                  <p className="text-muted-foreground mt-1">Tell your audience who you are</p>
                </div>

                <div className="flex items-center gap-4">
                  <div className="relative group cursor-pointer" onClick={() => fileInputRef.current?.click()}>
                    <Avatar className="w-20 h-20">
                      {avatarUrl ? <AvatarImage src={avatarUrl} /> : null}
                      <AvatarFallback className="text-2xl font-display font-bold">
                        {displayName?.[0]?.toUpperCase() || "?"}
                      </AvatarFallback>
                    </Avatar>
                    <div className="absolute inset-0 rounded-full bg-foreground/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                      <Camera className="w-5 h-5 text-background" />
                    </div>
                    <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handleAvatarUpload} />
                  </div>
                  <p className="text-sm text-muted-foreground">{uploading ? "Uploading..." : "Upload a profile photo"}</p>
                </div>

                <div>
                  <Label>Username *</Label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">verifiedly.app/</span>
                    <Input
                      value={username}
                      onChange={e => setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, "").toLowerCase())}
                      required
                      className="pl-[110px]"
                      placeholder="username"
                    />
                  </div>
                  {username.length >= 3 && (
                    <p className={`text-xs mt-1 ${checkingUsername ? "text-muted-foreground" : usernameAvailable ? "text-primary" : "text-destructive"}`}>
                      {checkingUsername ? "Checking..." : usernameAvailable ? "✓ Available" : "✗ Username taken"}
                    </p>
                  )}
                </div>

                <div><Label>Display Name *</Label><Input value={displayName} onChange={e => setDisplayName(e.target.value)} placeholder="Your Name" /></div>
                <div><Label>Bio</Label><Textarea value={bio} onChange={e => setBio(e.target.value)} rows={3} placeholder="Tell your fans about yourself..." /></div>
                <div className="grid grid-cols-2 gap-3">
                  <div><Label>Instagram</Label><Input value={instagram} onChange={e => setInstagram(e.target.value)} placeholder="@username" /></div>
                  <div><Label>Twitter / X</Label><Input value={twitter} onChange={e => setTwitter(e.target.value)} placeholder="@username" /></div>
                  <div><Label>YouTube</Label><Input value={youtube} onChange={e => setYoutube(e.target.value)} placeholder="Channel URL" /></div>
                  <div><Label>TikTok</Label><Input value={tiktok} onChange={e => setTiktok(e.target.value)} placeholder="@username" /></div>
                </div>
              </div>
            )}

            {step === 2 && (
              <div className="space-y-6">
                <div>
                  <h1 className="text-2xl font-display font-bold">Add your links</h1>
                  <p className="text-muted-foreground mt-1">These will appear on your profile as clickable cards</p>
                </div>

                <Card className="p-4 space-y-3">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    <div><Label>Title</Label><Input value={newLinkTitle} onChange={e => setNewLinkTitle(e.target.value)} placeholder="My Latest Video" /></div>
                    <div><Label>URL</Label><Input value={newLinkUrl} onChange={e => setNewLinkUrl(e.target.value)} placeholder="https://..." /></div>
                  </div>
                  <div className="flex gap-3 items-end">
                    <div><Label>Icon (emoji)</Label><Input value={newLinkIcon} onChange={e => setNewLinkIcon(e.target.value)} placeholder="🔗" className="w-20" /></div>
                    <Button onClick={addLink} disabled={!newLinkTitle.trim() || !newLinkUrl.trim()} className="gap-1"><Plus className="w-4 h-4" /> Add</Button>
                  </div>
                </Card>

                <div className="space-y-2">
                  {links.map((link, i) => (
                    <Card key={i} className="p-3 flex items-center gap-3">
                      <span>{link.icon}</span>
                      <div className="flex-1 min-w-0">
                        <p className="font-semibold text-sm truncate">{link.title}</p>
                        <p className="text-xs text-muted-foreground truncate">{link.url}</p>
                      </div>
                      <Button variant="ghost" size="sm" onClick={() => removeLink(i)}><Trash2 className="w-4 h-4" /></Button>
                    </Card>
                  ))}
                  {links.length === 0 && <p className="text-center text-muted-foreground py-6 text-sm">No links yet. You can always add them later.</p>}
                </div>
              </div>
            )}

            {needsStripe && step === 3 && (
              <div className="space-y-6">
                <div>
                  <h1 className="text-2xl font-display font-bold">Connect your payout account</h1>
                  <p className="text-muted-foreground mt-1">
                    Set up Stripe to receive payments from product sales, tips, and subscriptions.
                    You can skip this for now and set it up later from your settings.
                  </p>
                </div>

                {stripeConnected ? (
                  <Card className="p-6 text-center space-y-3">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mx-auto">
                      <Check className="w-8 h-8 text-primary" />
                    </div>
                    <h3 className="font-display font-semibold text-lg">Stripe Connected!</h3>
                    <p className="text-sm text-muted-foreground">
                      Your payout account is set up. You'll receive payments directly to your bank account.
                    </p>
                    {userId && <div className="mt-4 text-left"><PayoutsChecklist userId={userId} variant="compact" /></div>}
                  </Card>
                ) : (
                  <Card className="p-6 space-y-4">
                    <div className="space-y-2">
                      <h3 className="font-display font-semibold">Why connect Stripe?</h3>
                      <ul className="space-y-2 text-sm text-muted-foreground">
                        <li className="flex items-start gap-2">
                          <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          Get paid directly to your bank account
                        </li>
                        <li className="flex items-start gap-2">
                          <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          Accept credit cards, Apple Pay, and more
                        </li>
                        <li className="flex items-start gap-2">
                          <Check className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          Automatic payouts — no manual withdrawals
                        </li>
                      </ul>
                    </div>
                    <label className="flex items-start gap-3 p-3 rounded-lg border border-border bg-muted/30 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={stripeAgreed}
                        onChange={(e) => setStripeAgreed(e.target.checked)}
                        className="mt-1 w-4 h-4 accent-primary cursor-pointer"
                      />
                      <span className="text-xs leading-relaxed text-muted-foreground">
                        I agree to the{" "}
                        <a
                          href="https://stripe.com/legal/connect-account"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="underline text-foreground hover:opacity-70"
                        >
                          Stripe Connected Account Agreement
                        </a>{" "}
                        and{" "}
                        <a
                          href="https://stripe.com/legal/ssa"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="underline text-foreground hover:opacity-70"
                        >
                          Stripe Services Agreement
                        </a>
                        , and to Verifiedly's{" "}
                        <a href="/terms" target="_blank" className="underline text-foreground hover:opacity-70">
                          Terms
                        </a>{" "}
                        and{" "}
                        <a href="/refunds" target="_blank" className="underline text-foreground hover:opacity-70">
                          Refund Policy
                        </a>
                        . I understand I am the merchant of record for my sales.
                      </span>
                    </label>
                    <Button
                      onClick={handleStripeConnect}
                      disabled={stripeConnecting || !stripeAgreed}
                      className="w-full"
                      size="lg"
                    >
                      {stripeConnecting ? "Setting up..." : "Connect Stripe Account"}
                    </Button>
                    <p className="text-xs text-muted-foreground text-center">
                      You'll be redirected to Stripe to complete setup securely.
                    </p>
                  </Card>
                )}
                {!stripeConnected && (
                  <p className="text-xs text-muted-foreground text-center">
                    Not ready? You can skip this and connect Stripe later from your dashboard settings.
                  </p>
                )}
              </div>
            )}

            {step === (needsStripe ? 4 : 3) && (
              <div className="space-y-6">
                <div>
                  <h1 className="text-2xl font-display font-bold">Choose your theme</h1>
                  <p className="text-muted-foreground mt-1">Pick a style for your public profile</p>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  {THEMES.map(t => (
                    <button
                      key={t.id}
                      onClick={() => setTheme(t.id)}
                      className={`rounded-xl border-2 p-4 text-center transition-all ${theme === t.id ? "border-primary ring-2 ring-primary/20" : "border-border hover:border-muted-foreground/30"}`}
                    >
                      <div className={`${t.bg} rounded-lg h-20 mb-2 flex items-end justify-center p-2`}>
                        <div className={`${t.accent} rounded-full h-3 w-12`} />
                      </div>
                      <p className="text-sm font-medium">{t.label}</p>
                      {theme === t.id && <Check className="w-4 h-4 mx-auto mt-1 text-primary" />}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </motion.div>
        </AnimatePresence>
      </div>

      <div className="border-t border-border bg-background sticky bottom-0">
        <div className="container mx-auto max-w-2xl px-4 py-4 flex justify-between">
          <Button variant="ghost" onClick={() => setStep(step - 1)} disabled={step === 0} className="gap-1">
            <ChevronLeft className="w-4 h-4" /> Back
          </Button>
          {step < steps.length - 1 ? (
            <Button onClick={() => setStep(step + 1)} disabled={!canProceed()} className="gap-1">
              Next <ChevronRight className="w-4 h-4" />
            </Button>
          ) : (
            <Button onClick={handleFinish} disabled={saving} className="gap-1">
              {saving ? "Setting up..." : "Finish Setup"} <Check className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>
    </div>
  );
};

export default Onboarding;
